### ISSUE TITLE
Find a better way to stop the built-in engine

### ISSUE THREAD

**Issue by swarn** [swarn/semanticist.nvim#1]
This hack from the README:
``` lua
vim.defer_fn(function() vim.lsp.semantic_tokens.stop(buffer, client.id) end, 50)
```
The "wait a bit and hope that `start` has occurred" strategy isn't great.

**Comment by swarn** [comment]
@jdrouhard, I hope you don't mind me pinging you here about code that I ~stole~ reused from your PR. I don't know if there's a good way to:
1. Keep the built-in engine from starting, because the current method (deleting `semanticTokensProvider`) would keep this from working.
2. Trigger the `stop()` call automatically after the built-in engine starts.

**Comment by jdrouhard** [comment]
What I ended up doing in the meantime until we can come to some sort of consensus and get something merged to main is in my [dotfiles](https://github.com/jdrouhard/dotfiles/blob/try_lazy/home/dot_config/nvim/lua/plugins/lsp/semantic_tokens.lua). 

The override transformer thing was just sort of a hack, if I made this a real plugin I was going to clean that up. The main idea is that you only have to replace the `on_win` function and everything else still just works. The default transformer in that file does exactly what neovim HEAD does. See my `theme.lua` and `lsp/init.lua` files for how I integrated it and how I'm using it.

**Comment by jdrouhard** [comment]
This plugin would work better if you made it neovim 0.9 only and did what I do in my dotfiles. Much simpler I think.

**Comment by swarn** [comment]
Ah, monkey-patching the `on_win` function is far better than replicating the entire engine. I should have thought to look at your dotfiles. I will switch to that as soon as I'm using nightly for daily driving; I'm letting the TUI changes settle for a while.

Many thanks!

**Comment by swarn** [comment]
Done. There's a simple table of highlighter functions, indexed by filetype, used by the custom `on_win` function.
